'use strict';
// `yay gate` — bootstrap the enforcement gate for a project:
//   • write a GitHub Actions workflow that runs `yay verify --strict` on PRs,
//   • optionally install a local pre-push hook for solo/offline feedback,
//   • print the branch-protection steps (which live in GitHub settings and
//     can't be scripted with a normal token).
// String generators are pure (easy to test); file writes are separate.

const fs = require('fs');
const path = require('path');

const WORKFLOW_REL = '.github/workflows/yaylayer.yml';

function ciWorkflow({ pkg = 'yay-layer', scope = '', root = '' } = {}) {
  const scopeArg = (scope ? ` --dir ${scope}` : '') + (root ? ` --root ${root}` : '');
  return `# Generated by \`yay gate\`. The real gate is this check PLUS a branch-protection
# rule on main that REQUIRES the "gate" check (see the printed steps).
# NOTE: until yay-layer is published to npm, change the install line to:
#   run: npm install -g github:jonas-developer/yay-layer
name: YayLayer
on:
  pull_request:
  push:
    branches: [main]
jobs:
  gate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install YayLayer
        run: npm install -g ${pkg}
      - name: Verify the gate
        run: yay verify --strict${scopeArg}
`;
}

function prePushHook({ scope = '' } = {}) {
  const scopeArg = scope ? ` --dir ${scope}` : '';
  return `#!/bin/sh
# YayLayer local gate — refuses a push while any Cell is Red / Unsigned / Pink.
# This is fast local feedback, NOT the real guarantee (bypass with: git push --no-verify).
# The real gate is the CI check + branch protection on main.
command -v yay >/dev/null 2>&1 || { echo "yaylayer: 'yay' not on PATH — skipping local gate"; exit 0; }
yay verify --strict${scopeArg} || {
  echo ""
  echo "  push blocked by YayLayer — resolve Red/Unsigned/Pink (yay verify --problems), or: git push --no-verify"
  exit 1
}
`;
}

function branchProtectionSteps() {
  return [
    'To make it enforce, require the check on main (one-time, in the browser):',
    '',
    '  1. Push this workflow to main FIRST (while main is still unprotected), and let',
    '     it run once — the "gate" check only becomes selectable after it has run.',
    '  2. GitHub → your repo → Settings → Rules → Rulesets → New ruleset → New branch ruleset.',
    '  3. Name it (e.g. "main gate"); Enforcement: Active.',
    '  4. Target branches → Add target → Include default branch (main).',
    '  5. Tick: Require a pull request before merging.',
    '  6. Tick: Require status checks to pass → search & select  gate  .',
    '  7. Tick: Block force pushes.  Then Create.',
    '',
    'Now nothing merges to main until the gate is green (no Red / Unsigned / Pink; Yellow is allowed).',
    'Branch protection lives in GitHub settings only you control — a token cannot set it.',
  ].join('\n');
}

// Write the workflow file. Idempotent: skips an existing file unless force.
function writeWorkflow(root, opts = {}) {
  const abs = path.join(root, WORKFLOW_REL);
  if (fs.existsSync(abs) && !opts.force) return { action: 'skipped', path: WORKFLOW_REL };
  fs.mkdirSync(path.dirname(abs), { recursive: true });
  const existed = fs.existsSync(abs);
  fs.writeFileSync(abs, ciWorkflow(opts));
  return { action: existed ? 'overwritten' : 'created', path: WORKFLOW_REL };
}

// Install the pre-push hook. Idempotent unless force; needs a git repo.
function writeHook(root, opts = {}) {
  const dir = path.join(root, '.git', 'hooks');
  if (!fs.existsSync(path.join(root, '.git'))) return { action: 'no-git', path: '.git/hooks/pre-push' };
  const abs = path.join(dir, 'pre-push');
  if (fs.existsSync(abs) && !opts.force) return { action: 'skipped', path: '.git/hooks/pre-push' };
  fs.mkdirSync(dir, { recursive: true });
  fs.writeFileSync(abs, prePushHook(opts));
  try { fs.chmodSync(abs, 0o755); } catch (_) {}
  return { action: 'created', path: '.git/hooks/pre-push' };
}

module.exports = { ciWorkflow, prePushHook, branchProtectionSteps, writeWorkflow, writeHook, WORKFLOW_REL };
