'use strict';
// `yay gate` — bootstrap the enforcement gate for a project on ANY git host:
//   • write the CI pipeline that runs `yay verify --strict` on PRs/MRs,
//   • optionally install a local pre-push hook for solo/offline feedback,
//   • print the branch-protection steps (which live in the host's settings and
//     can't be scripted with a normal token).
// The gate itself is platform-agnostic — the ONLY host-specific part is the pipeline
// file's syntax and where branch protection lives. `--for <platform>` picks that.
// String generators are pure (easy to test); file writes are separate.

const fs = require('fs');
const path = require('path');

const WORKFLOW_REL = '.github/workflows/yaylayer.yml'; // default (github), kept for back-compat
const NPM_NOTE = "# Until yay-layer is published to npm, change the install line to:  npm install -g github:jonas-developer/yay-layer";
const args = ({ scope = '', root = '' }) => (scope ? ` --dir ${scope}` : '') + (root ? ` --root ${root}` : '');

// ── per-platform CI pipeline generators (all just: install node → install yay → verify --strict) ──
function githubWorkflow(o = {}) {
  return `# Generated by \`yay gate\`. The real gate is this check PLUS a branch-protection rule on
# main that REQUIRES the "gate" check (see the printed steps).
${NPM_NOTE}
name: YayLayer
on:
  pull_request:
  push:
    branches: [main]
jobs:
  gate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install YayLayer
        run: npm install -g ${o.pkg || 'yay-layer'}
      - name: Verify the gate
        run: yay verify --strict${args(o)}
`;
}
function azureWorkflow(o = {}) {
  return `# Generated by \`yay gate --for azure\`. The real gate is this pipeline PLUS a Branch Policy
# on main that REQUIRES it (Repos → Branches → main → Branch policies → Build Validation).
${NPM_NOTE}
trigger:
  branches: { include: [main] }
pr:
  branches: { include: [main] }
pool:
  vmImage: ubuntu-latest
steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '20.x'
  - script: npm install -g ${o.pkg || 'yay-layer'}
    displayName: Install YayLayer
  - script: yay verify --strict${args(o)}
    displayName: YayLayer gate
`;
}
function gitlabWorkflow(o = {}) {
  return `# Generated by \`yay gate --for gitlab\`. The real gate is this job PLUS a Protected branch on
# main with "Pipelines must succeed" + merge-request approvals (Settings → Repository / Merge requests).
${NPM_NOTE}
stages: [verify]
yaylayer-gate:
  stage: verify
  image: node:20
  script:
    - npm install -g ${o.pkg || 'yay-layer'}
    - yay verify --strict${args(o)}
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
    - if: '$CI_COMMIT_BRANCH == "main"'
`;
}
function bitbucketWorkflow(o = {}) {
  const step = `      - step:\n          name: YayLayer gate\n          script:\n            - npm install -g ${o.pkg || 'yay-layer'}\n            - yay verify --strict${args(o)}`;
  return `# Generated by \`yay gate --for bitbucket\`. The real gate is this pipeline PLUS a Branch
# restriction on main requiring a passing build + a PR (Repository settings → Branch restrictions).
${NPM_NOTE}
image: node:20
pipelines:
  pull-requests:
    '**':
${step}
  branches:
    main:
${step}
`;
}

// gitea/forgejo run GitHub-Actions-compatible workflows — same content, different path.
const PLATFORMS = {
  github: { rel: '.github/workflows/yaylayer.yml', workflow: githubWorkflow },
  gitea: { rel: '.gitea/workflows/yaylayer.yml', workflow: githubWorkflow },
  azure: { rel: 'azure-pipelines.yml', workflow: azureWorkflow },
  gitlab: { rel: '.gitlab-ci.yml', workflow: gitlabWorkflow },
  bitbucket: { rel: 'bitbucket-pipelines.yml', workflow: bitbucketWorkflow },
};
const PLATFORM_KEYS = Object.keys(PLATFORMS);
const normPlatform = (p) => { const k = String(p || 'github').toLowerCase().replace('devops', '').replace('forgejo', 'gitea').trim(); return PLATFORMS[k] ? k : (k === 'ado' ? 'azure' : 'github'); };

// Back-compat: the bare github generator.
function ciWorkflow(o = {}) { return (PLATFORMS[normPlatform(o.platform)] || PLATFORMS.github).workflow(o); }

function prePushHook({ scope = '' } = {}) {
  const scopeArg = scope ? ` --dir ${scope}` : '';
  return `#!/bin/sh
# YayLayer local gate — refuses a push while any Cell is Red / Unsigned / Pink.
# This is fast local feedback, NOT the real guarantee (bypass with: git push --no-verify).
# The real gate is the CI check + branch protection on main.
command -v yay >/dev/null 2>&1 || { echo "yaylayer: 'yay' not on PATH — skipping local gate"; exit 0; }
yay verify --strict${scopeArg} || {
  echo ""
  echo "  push blocked by YayLayer — resolve Red/Unsigned/Pink (yay verify --problems), or: git push --no-verify"
  exit 1
}
`;
}

function branchProtectionSteps(platform) {
  const p = normPlatform(platform);
  const common = 'Now nothing merges to main until the gate is green (no Red / Unsigned / Pink; Yellow is allowed).\nBranch protection lives in your host\'s settings only you control — a token cannot set it.';
  if (p === 'azure') return [
    'To make it enforce, add a Branch Policy on main (one-time, in Azure DevOps):',
    '',
    '  1. Commit azure-pipelines.yml, then Pipelines → New pipeline → point it at this repo/file and run it once.',
    '  2. Repos → Branches → hover main → ⋯ → Branch policies.',
    '  3. Build Validation → + → pick this pipeline; Trigger: Automatic; Policy requirement: Required.',
    '  4. Also enable "Require a minimum number of reviewers" (≥1) so changes go through a PR.',
    '', common,
  ].join('\n');
  if (p === 'gitlab') return [
    'To make it enforce (one-time, in GitLab):',
    '',
    '  1. Commit .gitlab-ci.yml and let a pipeline run once.',
    '  2. Settings → Repository → Protected branches → protect main (Allowed to merge: Maintainers).',
    '  3. Settings → Merge requests → tick "Pipelines must succeed"; set required approvals ≥ 1.',
    '', common,
  ].join('\n');
  if (p === 'bitbucket') return [
    'To make it enforce (one-time, in Bitbucket):',
    '',
    '  1. Commit bitbucket-pipelines.yml (enable Pipelines in Repository settings) and let it run once.',
    '  2. Repository settings → Branch restrictions → add a restriction on main.',
    '  3. Require: a pull request, a minimum number of approvals (≥1), and "successful builds" before merging.',
    '', common,
  ].join('\n');
  if (p === 'gitea') return [
    'To make it enforce (one-time, in Gitea/Forgejo):',
    '',
    '  1. Commit .gitea/workflows/yaylayer.yml (enable Actions for the repo) and let it run once.',
    '  2. Settings → Branches → Branch protection → add a rule for main.',
    '  3. Enable "Require status checks" → add the "gate" check; require a PR + approvals.',
    '', common,
  ].join('\n');
  // github (default)
  return [
    'To make it enforce, require the check on main (one-time, in the browser):',
    '',
    '  1. Push this workflow to main FIRST (while main is still unprotected), and let',
    '     it run once — the "gate" check only becomes selectable after it has run.',
    '  2. GitHub → your repo → Settings → Rules → Rulesets → New ruleset → New branch ruleset.',
    '  3. Name it (e.g. "main gate"); Enforcement: Active.',
    '  4. Target branches → Add target → Include default branch (main).',
    '  5. Tick: Require a pull request before merging.',
    '  6. Tick: Require status checks to pass → search & select  gate  .',
    '  7. Tick: Block force pushes.  Then Create.',
    '', common,
  ].join('\n');
}

// Write the pipeline file for the chosen platform. Idempotent: skips an existing file unless force.
function writeWorkflow(root, opts = {}) {
  const plat = PLATFORMS[normPlatform(opts.platform)] || PLATFORMS.github;
  const abs = path.join(root, plat.rel);
  if (fs.existsSync(abs) && !opts.force) return { action: 'skipped', path: plat.rel };
  fs.mkdirSync(path.dirname(abs), { recursive: true });
  const existed = fs.existsSync(abs);
  fs.writeFileSync(abs, plat.workflow(opts));
  return { action: existed ? 'overwritten' : 'created', path: plat.rel };
}

// Install the pre-push hook. Idempotent unless force; needs a git repo.
function writeHook(root, opts = {}) {
  const dir = path.join(root, '.git', 'hooks');
  if (!fs.existsSync(path.join(root, '.git'))) return { action: 'no-git', path: '.git/hooks/pre-push' };
  const abs = path.join(dir, 'pre-push');
  if (fs.existsSync(abs) && !opts.force) return { action: 'skipped', path: '.git/hooks/pre-push' };
  fs.mkdirSync(dir, { recursive: true });
  fs.writeFileSync(abs, prePushHook(opts));
  try { fs.chmodSync(abs, 0o755); } catch (_) {}
  return { action: 'created', path: '.git/hooks/pre-push' };
}

module.exports = { ciWorkflow, prePushHook, branchProtectionSteps, writeWorkflow, writeHook, WORKFLOW_REL, PLATFORMS, PLATFORM_KEYS, normPlatform };
